### ISSUE TITLE
Vector export or High resolution wordcloud

### ISSUE THREAD

**Issue by kakakhan2016** [Lchiffon/wordcloud2#14]
Thanks for awesome work. Kindly guide me how can generated wordcloud can be export as vector. I have already created PDF file using saveWidget and webshot code but PDF contain raster image not vector. 

If vector export from html5 canvas is not possible than how can I render high resolution wordcloud.  Increasing size parameter is also not helpful as wordcloud is only visible in shown browser page. I have also tried to export from RStudio but image dimension can be set maximum to 1200 pixles.  I need wordcloud in size atleast of 2500pxx2500px

**Comment by Lchiffon** [comment]
```
install.packages("webshot")
webshot::install_phantomjs()
library(wordcloud2)
hw = wordcloud2(demoFreq,size = 3)
saveWidget(hw,"1.html",selfcontained = F)
webshot::webshot("1.html","1.png",vwidth = 1992, vheight = 1744, delay =10)
```

**Comment by kakakhan2016** [comment]
Thanks Lchiffon. Previously I have already tried this code but wordcloud size was 1. Wordcloud size of 3 works great.
