### ISSUE TITLE
No picture obtained after running letterCloud () or using Custom (user-defined) picture.

### ISSUE THREAD

**Issue by yujuanzhang** [Lchiffon/wordcloud2#22]
（1）	No picture obtained after running letterCloud () or using Custom (user-defined) picture. Anyone can help me?  运用教程中的例子，当运行letterCloud ()或采用自定义的图片时，没用结果输出。
（2）	How to save .pdf result from .html result? 其它情况都有web页的词云图出现，但是怎么保存为.pdf?

**Comment by Lchiffon** [comment]
#8 
#12
