### ISSUE TITLE
Don't change user locale

### ISSUE THREAD

**Issue by jeroen** [Lchiffon/wordcloud2#3]
See [zzz.R](https://github.com/Lchiffon/wordcloud2/blob/master/R/zzz.R). This can have really bad side effects for the user and other packages.

Nice package by the way :)

**Comment by Lchiffon** [comment]
Thanks~

I've deleted `sys.setlocate`.

The only reason of using `sys.setlocate` is wordcloud of Chinese character can only be used by windows user when `LC_CTYPE = eng`  ):
