### ISSUE TITLE
Multiple wordclouds not plotting in 0.2.1

### ISSUE THREAD

**Issue by AdamSpannbauer** [Lchiffon/wordcloud2#34]
I created a simple example before to demonstrate an issue with hover info in previous versions (#18).  This example no longer works in the newest version on CRAN.  When I run this only one of the 4 wordclouds is plotted in the shiny app.

I have not yet had time to investigate what's causing the issue

Small reproducible example.
```
library(shiny)
library(wordcloud2)
shinyApp(
  ui=shinyUI(fluidPage(
    fluidRow(
      column(width=6,align="center", wordcloud2Output("my_wc")),
      column(width=6,align="center", wordcloud2Output("my_wc2"))
    ),
    wordcloud2Output("my_wc3"),
    wordcloud2Output("my_wc4")
  )),
  server=shinyServer(function(input,output,session){
    output$my_wc  = renderWordcloud2(wordcloud2(demoFreq))
    output$my_wc2 = renderWordcloud2(wordcloud2(demoFreq))
    output$my_wc3 = renderWordcloud2(wordcloud2(demoFreq))
    output$my_wc4 = renderWordcloud2(wordcloud2(demoFreq))
  })
)
```

**Comment by AdeelK93** [comment]
Updated #32 to fix this, it's an issue with how the chart object is returned in the R code

**Comment by AdamSpannbauer** [comment]
this should be fixed now that #32 has been merged

**Comment by rfsaldanha** [comment]
The reproducible example from @AdamSpannbauer does not work with version 0.2.2

**Comment by AdamSpannbauer** [comment]
@rfsaldanha what browser are you using?

The example runs fine for me in the following broswers:

* Firefox 64.0.2
* Chrome 71.0.3578.98
* Safari 12.0.2

abridged `sessionInfo()`:
```
R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.2

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] wordcloud2_0.2.2 shiny_1.2.0
```

**Comment by rfsaldanha** [comment]
@AdamSpannbauer I update some packages and worked. Sorry for troubling you.
