### ISSUE TITLE
Lettercloud 画图只有背景色

### ISSUE THREAD

**Issue by ShiMingMing1213** [Lchiffon/wordcloud2#39]
现在出现了这个问题，letterCloud(demoFreqC,word="R",size = 1) 出来之后没有颜色，只有形状没有颜色，如下图，是怎么回事？
![c8c6a2efce1b9d166db09ebdf8deb48f8d5464f3](https://user-images.githubusercontent.com/31852964/35897402-fa69d318-0bfb-11e8-8fe2-4f03a25efdd0.jpg)
![c8c6a2efce1b9d166db09ebdf8deb48f8d5464f3](https://user-images.githubusercontent.com/31852964/35897408-ff826c48-0bfb-11e8-8954-f079f0fc94d0.jpg)

**Comment by akeyboardlife** [comment]
#12

直接从github安装

**Comment by jacobyxu** [comment]
try `devtools::install_github("JacobXPX/wordcloud2")`
