### ISSUE TITLE
Wordcloud2 in R

### ISSUE THREAD

**Issue by kaantoprak58** [Lchiffon/wordcloud2#43]
hello, i study on Text mining and i do not know how can i create number wordcloud2. I know shape of star or peace. But i can not number 10 as shape of wordcloud. Can you help me? 

wordcloud2::wordcloud2(asd,word="R", color='random-light' , backgroundColor="black") it is okey. but 
wordcloud2::wordcloud2(asd,figPath="10.png", color='random-light' , backgroundColor="black") does not work.

**Comment by Lchiffon** [comment]
use `letterCloud` instead

```r
letterCloud(demoFreq, word = '10')
```

![image](https://user-images.githubusercontent.com/7221728/41588309-f42dbc4e-73e3-11e8-8129-32b220f32272.png)
