### ISSUE TITLE
Issues with Hover and Click

### ISSUE THREAD

**Issue by AdamSpannbauer** [Lchiffon/wordcloud2#45]
The most recent merged PR from @JacobXPX seems to have issues with hover info and issues with click events when rendering multiple wordcloud2s.  I have not yet had time to look into what causes the issue, but I know the issues weren't present in my initial PR (based on the example apps shown below).

Please let me know if these issues are not reproducible or if they are due to user error.  If these are consistent issues then I think they should be resolved before the next push to CRAN.

All example output below are from running the github version of wordcloud2 in Chrome.

#### Issues with multiple wordcloud2s:

* No hover info displayed
* Clicking a word in either wordcloud2 updates both input clicked words

```r
devtools::install_github('Lchiffon/wordcloud2')

library(shiny)
library(wordcloud2)
shinyApp(
  ui=shinyUI(fluidPage(
    #using default clicked word input id
    wordcloud2Output("my_wc"),
    #using custom clicked word input id
    wordcloud2Output("my_wc2", clickedWordInputId = "wc2_clicked_word"),
    
    verbatimTextOutput("print"),
    verbatimTextOutput("print2")
  )),
  server=shinyServer(function(input,output,session){
    output$my_wc  = renderWordcloud2(wordcloud2(demoFreq))
    output$my_wc2 = renderWordcloud2(wordcloud2(demoFreq))
    
    #using default clicked word input id
    output$print  = renderPrint(input$selected_word)
    #using custom clicked word input id
    output$print2 = renderPrint(input$wc2_clicked_word)
  })
)
```

<img src=https://user-images.githubusercontent.com/16326083/41597042-4fcd978a-739a-11e8-9dc4-5691b89cf5f8.gif width=500>

#### Issues with single wordcloud2

* Hover info is displayed incorrectly at bottom left corner of the wordcloud2 html widget

```r
devtools::install_github('Lchiffon/wordcloud2')

library(shiny)
library(wordcloud2)
shinyApp(
  ui=shinyUI(fluidPage(
    #using default clicked word input id
    wordcloud2Output("my_wc"),
    
    verbatimTextOutput("print")
  )),
  server=shinyServer(function(input,output,session){
    output$my_wc  = renderWordcloud2(wordcloud2(demoFreq))

    #using default clicked word input id
    output$print  = renderPrint(input$selected_word)
  })
)

```

<img src=https://user-images.githubusercontent.com/16326083/41597273-f7f6855c-739a-11e8-81f9-0e117bb98819.gif width=500>

**Comment by AdamSpannbauer** [comment]
At a glance it looks like the changes @JacobXPX made to the [hover.js](https://github.com/Lchiffon/wordcloud2/blob/master/inst/htmlwidgets/lib/wordcloud2-0.0.1/hover.js) file essentially undoes all the changes @AdeelK93 made to ensure unique wordcloud2 ids in PR #32 (which fixed issue #18)

**Comment by jacobyxu** [comment]
Respected all,

As I remembered, when I used it, It's not clickable and not showing hover info.That's the reason why I
undoes it. I'm using Ubuntu, also test on firefox.

Thank you!

**Comment by AdamSpannbauer** [comment]
Testing in Firefox gives me about the same issues as described above.  

Of note, I reverted back to an [earlier commit](https://github.com/Lchiffon/wordcloud2/commit/d9a604611d588d5a89f6026b813b1e0a5e5ccf94) (before the revisions to [hover.js](https://github.com/Lchiffon/wordcloud2/blob/master/inst/htmlwidgets/lib/wordcloud2-0.0.1/hover.js)), and there are issues with click/hover in firefox, despite working well in chrome.

**Comment by jacobyxu** [comment]
I just fixed the firefox issue. Will try to fix the click on multiple clouds issue soon

**Comment by jacobyxu** [comment]
Hi Adam,

I have done finally, it works in Firefox perfectly. I will test it more later. [link](https://github.com/JacobXPX/wordcloud2), please have a look.

Updates:

feature          | firefox | chrome
---------------|------|---------
hover info  | work | work
multiple plot | work | work
separate click | work | work
special shape | work | not

**Comment by AdamSpannbauer** [comment]
Seems to be working great on my end!  Good stuff @JacobXPX

**Comment by AdamSpannbauer** [comment]
I think the work @JacobXPX fixes the reasons I had for opening this issue.  I'm going to close it.
