### ISSUE TITLE
shiny only one plot is showing

### ISSUE THREAD

**Issue by brunelserge** [Lchiffon/wordcloud2#59]
hello
when i want to plot two wordcloud on the same page only the first one is showing

i put ther description on stackoverflow [https://stackoverflow.com/questions/54943338/two-wordcloud2-on-the-same-shiny-page/54949680?noredirect=1#comment96732005_54949680](url)

the simple script

    library(wordcloud2)
    library(shiny)

    ui <- fluidPage(
        wordcloud2Output('wordcloud2'),
        wordcloud2Output('wordcloud3')
    )

    server <- function(input, output) {
        output$wordcloud2 <- renderWordcloud2({
                wordcloud2(demoFreq)
        })

        output$wordcloud3 <- renderWordcloud2({
                wordcloud2(demoFreq)
        })
    }

    shinyApp(ui = ui, server = server)`

when i check the html only the first one have "visibility: inherit"

![image](https://user-images.githubusercontent.com/5072903/53789433-a4564300-3f24-11e9-826d-e1f5784753ce.png)

**Comment by stragu** [comment]
Is this the same issue as https://github.com/Lchiffon/wordcloud2/issues/34 ?
It looks very similar, and if the issue is not reproducible with version 0.2.2, this should be closed.

**Comment by brunelserge** [comment]
it's working on 0.2.2 version yes, CRAN 0.2.1 isn't => closed
