### ISSUE TITLE
Locally exporting the wordclouds to png or svg format

### ISSUE THREAD

**Issue by DominiqueMakowski** [Lchiffon/wordcloud2#8]
Thank for your impressive work,

Do you know if there is any possibility to nicely save the cloud in png or svg format? Being able to change the resolution and such would be really nice :)

Cheers

**Comment by Lchiffon** [comment]
Currently, wordcloud2  can be exported by Rstudio:

Use the Export -> Save As Image menu within the RStudio Viewer (this
will let the user export a PNG of whatever size they need).

I'm still looking for a good method for exporting from R codes.

**Comment by Lchiffon** [comment]
I'll write a new function to solve exporting. You can try it like this:

```
install.packages("webshot")
webshot::install_phantomjs()
library(wordcloud2)
hw = wordcloud2(demoFreq,size = 3)
saveWidget(hw,"1.html",selfcontained = F)
webshot::webshot("1.html","1.png",vwidth = 1992, vheight = 1744, delay =10)
```

**Comment by badbye** [comment]
Save canvas to SVG: http://jsfiddle.net/pfp9y5xp/, hope it can be helpful.
